# 启动端口号
server:
  post: 8000

# MySQL数据源配置
mysql:
  username: root
  password: null
  url: tcp(localhost:3306)/imall?charset=utf8&parseTime=True&loc=Local

# 图片路径配置
upload:
  savePath: /Users/maoyachen/Code/waibao/mall/uploads/
  accessUrl: http://localhost:8000/image/

# JWT配置
jwt:
  signingKey: z3d6k8v0n3w7m9sa1fd0u09h

# 定时任务
cron:
  enable: true

# 微信小程序配置
code2Session:
  appId: wxfc2b51162bc78d32
  appSecret: 366f945ad63975344bff8f31097c8d5c

# 问题反馈配置
feedback:
  qqSmtp: smtp.qq.com
  qqEmail: 1933757688@qq.com
  qqEmailSecret: jjstmwtidhwhxhzc
